---
abstract: 'counting words in multilingual texts'
author:
  - 'Zbigniew Lukasiak <zlukasiak@opera.com>'
  - 'Tadeusz Sośnierz, tsosnierz@opera.com'
build_requires:
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-WordCounter
no_index:
  directory:
    - t/lib
requires:
  Lingua::Stem: 0
  Lingua::ZH::MMSEG: 0
  Moose: 0
  URI::Find: 0
  Unicode::UCD: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  repository: http://github.com/operasoftware/Text-WordCounter
version: 0.001
